### ISSUE TITLE
Nested Centered

### ISSUE THREAD

**Issue by clayellis** [everythird/infra#2]
I'd like to be able to center some text inside of a centered div.

Ideal usability would be:

`<body>`
`<div class="centered>`
       `<div class="centered>`
             `<h1>CENTERED TEXT</h1>`
        `</div>`
`</div>`
`</body>`

**Comment by rayelder** [comment]
Added .alignCenter class to avoid the need for a second <div> tag with .centered class.

<h1 class="alignCenter">Centered Text</h1>
